name: Build & test with Gradle

on:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: zulu

      - name: Build & test with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - if: matrix.os == 'ubuntu-latest'
        name: Run Test Coverage
        run: ./gradlew jacocoTestReport

      - if: matrix.os == 'ubuntu-latest'
        name: Jacoco Test Coverage Report
        uses: cicirello/jacoco-badge-generator@v2.8.0
        with:
          generate-branches-badge: true
          jacoco-csv-file: lib/build/jacoco/report.csv

